name: poc_example_integration
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  currency_text_input_formatter: ^2.0.1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.2.2+1
  google_sign_in: ^5.0.4
  graphql_flutter: ^5.0.0-nullsafety.5
  http: ^0.13.3
  intl: ^0.17.0
  mobx: ^2.0.1
  responsive_framework: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  flutter_modular_test: ^1.0.1
  mobx_codegen: ^2.0.1+3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/products/

  fonts:
    - family: IuppIcons
      fonts:
        - asset: assets/fonts/IuppIcons.ttf
        - asset: assets/fonts/IuppIcons.woff

    - family: ItauDisplay
      fonts:
        - asset: assets/fonts/ItauDisplay_Lt.ttf
          weight: 300
        - asset: assets/fonts/ItauDisplay_Rg.ttf
          weight: 400
        - asset: assets/fonts/ItauDisplay_Bd.ttf
          weight: 700
        - asset: assets/fonts/ItauDisplay_XBd.ttf
          weight: 800
        - asset: assets/fonts/ItauDisplay_He.ttf
          weight: 900

scripts:
  mobx: flutter pub run build_runner watch